Repository beeminder/BeeSwift, pull requests merged in 2020-08, with the labels that each got.

#110 signin screen clean up
  BeeSwift/Images.xcassets/website_logo_mid.imageset/Contents.json
  BeeSwift/Images.xcassets/website_logo_mid.imageset/website_logo_mid_type-5c8c74372ac413631e10ab410409a5fc9224027a9f88a31bd54788c2c663aadf.png
  BeeSwift/SignInViewController.swift
Labels: PEA, STY, UVI

#120 app has no use for HealthKit Capabilities Entitlement
  BeeSwift/BeeSwift.entitlements
Labels: BUG, HK

#126 repo cleanup remove googlesignin bundle
  BeeSwift.xcodeproj/project.pbxproj
  BeeSwift/GoogleSignIn.bundle/GTMOAuth2ViewTouch.nib
  BeeSwift/GoogleSignIn.bundle/Info.plist
  BeeSwift/GoogleSignIn.bundle/Roboto-Bold.ttf
  BeeSwift/GoogleSignIn.bundle/Roboto-Regular.ttf
  BeeSwift/GoogleSignIn.bundle/ar.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/ca.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/cs.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/da.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/de.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/el.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/en.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/en_GB.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/es.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/es_MX.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/fi.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/fr.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/google.png
  BeeSwift/GoogleSignIn.bundle/google@2x.png
  BeeSwift/GoogleSignIn.bundle/google@3x.png
  BeeSwift/GoogleSignIn.bundle/gplus.png
  BeeSwift/GoogleSignIn.bundle/gplus@2x.png
  BeeSwift/GoogleSignIn.bundle/gplus@3x.png
  BeeSwift/GoogleSignIn.bundle/he.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/hr.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/hu.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/id.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/it.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/ja.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/ko.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/ms.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/nb.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/nl.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/pl.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/pt.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/pt_BR.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/pt_PT.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/ro.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/ru.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/sk.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/sv.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/th.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/tr.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/uk.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/vi.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/zh_CN.lproj/GoogleSignIn.strings
  BeeSwift/GoogleSignIn.bundle/zh_TW.lproj/GoogleSignIn.strings
  README.md
Labels: ABC, STY

#128 use SafariViewController for when viewing goals externally
  BeeSwift/GoalViewController.swift
Labels: PEA, UVI

#138 elaborate on contributing guidelines
  CONTRIBUTING.md
  GETTING_STARTED.md
  README.md
Labels: ABC, STY, UVI

#139 [#25] more padding around the infinibee
  BeeSwift/Images.xcassets/AppIcon.appiconset/Contents.json
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon100.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon1024-1.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon114.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon120-1.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon120.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon144.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon152.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon180.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon58-1.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon58.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon76.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon80-1.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon80.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/Icon87.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_20pt.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_20pt@2x.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_20pt@3x.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_29pt.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_29pt@2x.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_29pt@3x.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_40pt.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_40pt@2x.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_40pt@3x.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_60pt@2x.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_60pt@3x.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_76pt.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_76pt@2x.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/icon_83.5@2x.png
  BeeSwift/Images.xcassets/AppIcon.appiconset/ios_giant_bee copy.png
Labels: ABC, PEA, STY

#149 update badge when signing out
  BeeSwift/AppDelegate.swift
Labels: PEA, STY, UVI

#156 bump Alamofire from 4.8.2 to 4.9.1
  Podfile
  Podfile.lock
  Pods/Alamofire/README.md
  Pods/Alamofire/Source/NetworkReachabilityManager.swift
  Pods/Alamofire/Source/Request.swift
  Pods/Alamofire/Source/Response.swift
  Pods/Alamofire/Source/ServerTrustPolicy.swift
  Pods/Alamofire/Source/Validation.swift
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Target Support Files/Alamofire/Alamofire-Info.plist
Labels: dependencies
